/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lock;

import java.awt.Color;
import javax.swing.JLabel;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.*;
import java.net.*;
import java.io.*;
/**
 *
 * @author sai
 */
public class lockgui extends javax.swing.JFrame {
    private static lockgui lk;
    private static int status;
    private static int count;
    
    public lockgui() {
        initComponents();
        /*this.k1.setVisible(false);
        this.k2.setVisible(false);
        this.k3.setVisible(false);
        this.k4.setVisible(false);
        this.k5.setVisible(false);*/
       
        
        
        try{
        //keys();
        }
        catch(Exception e)
        {
        System.out.println(e);
        }
        setLocation(new Point(((Toolkit.getDefaultToolkit().getScreenSize().width)-(this.getSize().width))/2,(Toolkit.getDefaultToolkit().getScreenSize().height-this.getSize().height)/2));
        //pnl2.setVisible(false);
    this.getContentPane().removeAll();
    this.pnl1.setSize(this.getSize().width,this.getSize().height);
    
    this.add(pnl1);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addjd = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        pnl1 = new javax.swing.JPanel();
        jtf1 = new javax.swing.JTextField();
        jpf1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        logbtn = new javax.swing.JButton();
        kybtn = new javax.swing.JButton();
        tbtn1 = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        pnl20 = new javax.swing.JPanel();
        pnl21 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dtf = new javax.swing.JTextField();
        mtf = new javax.swing.JTextField();
        ytf = new javax.swing.JTextField();
        gobtn = new javax.swing.JButton();
        pnl22 = new javax.swing.JLayeredPane();
        addbtn = new javax.swing.JButton();
        k1 = new javax.swing.JButton();
        k2 = new javax.swing.JButton();
        k3 = new javax.swing.JButton();
        k4 = new javax.swing.JButton();
        k5 = new javax.swing.JButton();

        addjd.setMinimumSize(new java.awt.Dimension(280, 161));
        addjd.setResizable(false);

        jTextField1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("Add");

        javax.swing.GroupLayout addjdLayout = new javax.swing.GroupLayout(addjd.getContentPane());
        addjd.getContentPane().setLayout(addjdLayout);
        addjdLayout.setHorizontalGroup(
            addjdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addjdLayout.createSequentialGroup()
                .addGroup(addjdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addjdLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addjdLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        addjdLayout.setVerticalGroup(
            addjdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addjdLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lock");
        setBackground(new java.awt.Color(0, 153, 255));
        setMinimumSize(new java.awt.Dimension(900, 561));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        pnl1.setBackground(new java.awt.Color(51, 153, 255));

        jtf1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jtf1.setForeground(new java.awt.Color(51, 51, 51));
        jtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf1ActionPerformed(evt);
            }
        });
        jtf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf1KeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Log in");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 0, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Password");

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(338, 338, 338))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnl1, "card2");

        pnl2.setBackground(new java.awt.Color(0, 153, 255));

        logbtn.setText("logs");
        logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbtnActionPerformed(evt);
            }
        });

        kybtn.setText("Keys");
        kybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kybtnActionPerformed(evt);
            }
        });

        tbtn1.setText("jButton8");
        tbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn1ActionPerformed(evt);
            }
        });

        lbl1.setText("jLabel1");

        pnl20.setBackground(new java.awt.Color(0, 153, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Time", "Access type", "Mode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        dtf.setText("DD");
        dtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtfActionPerformed(evt);
            }
        });

        mtf.setText("MM");

        ytf.setText("YYYY");

        gobtn.setText("go");

        javax.swing.GroupLayout pnl21Layout = new javax.swing.GroupLayout(pnl21);
        pnl21.setLayout(pnl21Layout);
        pnl21Layout.setHorizontalGroup(
            pnl21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl21Layout.createSequentialGroup()
                .addGroup(pnl21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl21Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(dtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(gobtn))
                    .addGroup(pnl21Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(447, Short.MAX_VALUE))
        );
        pnl21Layout.setVerticalGroup(
            pnl21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl21Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gobtn))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        pnl21.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnl21.setLayer(dtf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnl21.setLayer(mtf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnl21.setLayer(ytf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnl21.setLayer(gobtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pnl22.setOpaque(true);

        addbtn.setText("add key");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        k1.setText("jButton3");

        k2.setText("jButton4");

        k3.setText("jButton5");

        k4.setText("jButton6");

        k5.setText("jButton7");

        javax.swing.GroupLayout pnl22Layout = new javax.swing.GroupLayout(pnl22);
        pnl22.setLayout(pnl22Layout);
        pnl22Layout.setHorizontalGroup(
            pnl22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl22Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnl22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(k5)
                    .addComponent(k4)
                    .addComponent(k3)
                    .addComponent(k2)
                    .addComponent(k1)
                    .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(677, Short.MAX_VALUE))
        );
        pnl22Layout.setVerticalGroup(
            pnl22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl22Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(k1)
                .addGap(18, 18, 18)
                .addComponent(k2)
                .addGap(18, 18, 18)
                .addComponent(k3)
                .addGap(18, 18, 18)
                .addComponent(k4)
                .addGap(18, 18, 18)
                .addComponent(k5)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnl22.setLayer(addbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnl22.setLayer(k1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnl22.setLayer(k2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnl22.setLayer(k3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnl22.setLayer(k4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnl22.setLayer(k5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnl20Layout = new javax.swing.GroupLayout(pnl20);
        pnl20.setLayout(pnl20Layout);
        pnl20Layout.setHorizontalGroup(
            pnl20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 982, Short.MAX_VALUE)
            .addGroup(pnl20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl20Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(pnl20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl20Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnl20Layout.setVerticalGroup(
            pnl20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
            .addGroup(pnl20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl20Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(pnl20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl20Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnl22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(tbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(lbl1)
                        .addContainerGap(822, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                                .addComponent(logbtn)
                                .addGap(289, 289, 289))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                                .addComponent(kybtn)
                                .addGap(261, 261, 261))))))
            .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnl20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(lbl1))
                .addGap(277, 277, 277)
                .addComponent(logbtn)
                .addGap(72, 72, 72)
                .addComponent(kybtn)
                .addGap(143, 143, 143))
            .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                    .addContainerGap(97, Short.MAX_VALUE)
                    .addComponent(pnl20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        getContentPane().add(pnl2, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        pnl1.setVisible(false);
        this.add(pnl2);
        pnl2.setVisible(true);
                pnl22.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void logbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbtnActionPerformed
pnl22.setVisible(false);
pnl21.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_logbtnActionPerformed

    private void dtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtfActionPerformed

    private void kybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kybtnActionPerformed
pnl21.setVisible(false);
pnl22.setVisible(true); 
pnl2.revalidate();
// TODO add your handling code here:
    }//GEN-LAST:event_kybtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed

        addjd.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_addbtnActionPerformed

    private void tbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn1ActionPerformed
int u=3;
try{
    while(u==3)
     u=status;
if(u==1)
{
tbtn1.setText("ON");    
tbtn1.setEnabled(false);
while(lk.offupdate()!=6)
{Thread.sleep(1000);}

System.out.println("done");
tbtn1.setEnabled(true);
lbl1.setText("Off");

}
else if(u==2)
{
    tbtn1.setText("Off");
tbtn1.setEnabled(false);
while(lk.onupdate()!=6)
{Thread.sleep(1000);}


    System.out.println("done");
tbtn1.setEnabled(true);
   lbl1.setText("ON");

}
}
catch(Exception e)
{System.out.println(e);}
// TODO add your handling code here:
    }//GEN-LAST:event_tbtn1ActionPerformed

    private void jtf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf1KeyTyped

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
            /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lockgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lockgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lockgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lockgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       lk=new lockgui();
       lk.setVisible(true);
        while(true)
	 {
             lk.onoff();
             if(status==1)
          {
              lk.lbl1.setText("ON");
              lk.tbtn1.setText("OFF");
          }
          else if(status==2)
          {
          lk.tbtn1.setText("ON");
          lk.lbl1.setText("OFF");
          }
           Thread.sleep(1000);
	 }
         
    
    }
  private void remove(byte r)
  {
  count--;
  if(r==1)
  {
  
  }
  }
  private void onoff() throws Exception
  {
    int c;
    URL theURL = new URL("http://api.thingspeak.com/channels/28840/feeds/last.txt?key=PF87VU53HKRUJVE4");
    StringBuffer ds=new StringBuffer();
	 URLConnection theConn = theURL.openConnection();
         InputStream urlInput = theConn.getInputStream();
         while ((( c= urlInput.read()) != -1)) {
            ds.append((char)c);
         }
		 if(ds.charAt(ds.indexOf("@")+1)=='8')
                 status=1;
                     
                 else if(ds.charAt(ds.indexOf("@")+1)=='4')
                 status= 2;
                 else
                 status= 3;
                         
   }
  private void keys() throws MalformedURLException,IOException
  {
    
      URL theURL = new URL("http://api.thingspeak.com/channels/30501/feeds/last.txt?key=UAGRWNGCLSZFC1VN");
     int c;
	  int y=0;
	  int r=0;
	
	  StringBuffer ds=new StringBuffer();
	  URLConnection theConn = theURL.openConnection();
	 System.out.println();
         InputStream urlInput = theConn.getInputStream();
         while ((( c= urlInput.read()) != -1)) {
            ds.append((char)c);
         }
		 count=ds.charAt(ds.indexOf("\"field1\":\"")+10)-48;
                 if(count>0){
                 
                     k1.setVisible(true);
                      r=ds.indexOf("--",r+1);
                     k1.setText(ds.substring(r+2,ds.indexOf("--",r+3)));
                    
                 if(count>1)
                 {
                     k2.setVisible(true);
                      r=ds.indexOf("--",r+1);
                     k2.setText(ds.substring(r+2,ds.indexOf("--",r+3)));
                 }
                 if(count>2)
                 {
                     k3.setVisible(true);
                      r=ds.indexOf("--",r+1);
                     k3.setText(ds.substring(r+2,ds.indexOf("--",r+3)));
                 }
                 if(count>3)
                 {
                     k4.setVisible(true);
                      r=ds.indexOf("--",r+1);
                     k4.setText(ds.substring(r+2,ds.indexOf("--",r+3)));
                 }
                 if(count>4)
                 {
                     k5.setVisible(true);
                      r=ds.indexOf("--",r+1);
                     k5.setText(ds.substring(r+2,ds.indexOf("--",r+3)));
                 }
                 }
             
  
  }
  private int onupdate() throws MalformedURLException,IOException
          {
         int c;
         URL theURL = new URL("http://api.thingspeak.com//update?key=3HIDRE08RNE9L376&field1=@8&field2=$yyyyy");
         StringBuffer ds=new StringBuffer();
	 URLConnection theConn = theURL.openConnection();
         InputStream urlInput = theConn.getInputStream();
         while ((( c= urlInput.read()) != -1)) {
            ds.append((char)c);}
         System.out.println(ds);
            if(ds.length()==1){
            if(ds.equals("0")||ds.equals("-1"))
                return 9;}
            else if(ds.length()>1 && ds.length()<4)
            {System.out.println("return 6");return 6;}
            return 3;
          }
  private int offupdate() throws MalformedURLException,IOException
          {
         int c;
         URL theURL = new URL("http://api.thingspeak.com//update?key=3HIDRE08RNE9L376&field1=@4&field2=$yyyyy");
         StringBuffer ds=new StringBuffer();
	 URLConnection theConn = theURL.openConnection();
         InputStream urlInput = theConn.getInputStream();
         while ((( c= urlInput.read()) != -1)) {
            ds.append((char)c);}
            if(ds.length()==1)
            {if(ds.equals("0")||ds.equals("-1"))
                return 9;}
            else if(ds.length()>1 && ds.length()<4)
            {System.out.println("return 6");
                return 6;
            
            }
            
            return 3;
          }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JDialog addjd;
    private javax.swing.JTextField dtf;
    private javax.swing.JButton gobtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jpf1;
    private javax.swing.JTextField jtf1;
    private javax.swing.JButton k1;
    private javax.swing.JButton k2;
    private javax.swing.JButton k3;
    private javax.swing.JButton k4;
    private javax.swing.JButton k5;
    private javax.swing.JButton kybtn;
    private javax.swing.JLabel lbl1;
    private javax.swing.JButton logbtn;
    private javax.swing.JTextField mtf;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl20;
    private javax.swing.JLayeredPane pnl21;
    private javax.swing.JLayeredPane pnl22;
    private javax.swing.JButton tbtn1;
    private javax.swing.JTextField ytf;
    // End of variables declaration//GEN-END:variables
}
